### ISSUE TITLE
libv8 fails to install on OS X 10.11

### ISSUE THREAD

**Issue by cheba** [cowboyd/libv8#172]
Output:
```
Building native extensions.  This could take a while...
ERROR:  Error installing libv8:
	ERROR: Failed to build gem native extension.

    /Users/cheba/.rvm/rubies/ruby-2.2.2/bin/ruby -r ./siteconf20150625-46071-2hj7sd.rb extconf.rb
creating Makefile
Compiling v8 for x64
Using python 2.7.6
Using compiler: /usr/bin/c++ (clang version 7.0.0)
In file included from ../src/conversions.cc:32:
In file included from ../src/conversions-inl.h:43:
../src/scanner.h:444:5: error: unused typedef '__StaticAssertTypedef__444' [-Werror,-Wunused-local-typedef]
    STATIC_ASSERT(kCharacterLookaheadBufferSize == 1);
    ^
../src/checks.h:283:30: note: expanded from macro 'STATIC_ASSERT'
#define STATIC_ASSERT(test)  STATIC_CHECK(test)
                             ^
../src/checks.h:251:5: note: expanded from macro 'STATIC_CHECK'
    SEMI_STATIC_JOIN(__StaticAssertTypedef__, __LINE__)
    ^
../src/checks.h:240:32: note: expanded from macro 'SEMI_STATIC_JOIN'
#define SEMI_STATIC_JOIN(a, b) SEMI_STATIC_JOIN_HELPER(a, b)
                               ^
../src/checks.h:241:39: note: expanded from macro 'SEMI_STATIC_JOIN_HELPER'
#define SEMI_STATIC_JOIN_HELPER(a, b) a##b
                                      ^
<scratch space>:59:1: note: expanded from here
__StaticAssertTypedef__444
^
1 error generated.
make[1]: *** [/Users/cheba/.rvm/gems/ruby-2.2.2@libv8/gems/libv8-3.16.14.7/vendor/v8/out/x64.release/obj.target/preparser_lib/src/conversions.o] Error 1
make: *** [x64.release] Error 2
/Users/cheba/.rvm/gems/ruby-2.2.2@libv8/gems/libv8-3.16.14.7/ext/libv8/location.rb:36:in `block in verify_installation!': libv8 did not install properly, expected binary v8 archive '/Users/cheba/.rvm/gems/ruby-2.2.2@libv8/gems/libv8-3.16.14.7/vendor/v8/out/x64.release/obj.target/tools/gyp/libv8_base.a'to exist, but it was not found (Libv8::Location::Vendor::ArchiveNotFound)
	from /Users/cheba/.rvm/gems/ruby-2.2.2@libv8/gems/libv8-3.16.14.7/ext/libv8/location.rb:35:in `each'
	from /Users/cheba/.rvm/gems/ruby-2.2.2@libv8/gems/libv8-3.16.14.7/ext/libv8/location.rb:35:in `verify_installation!'
	from /Users/cheba/.rvm/gems/ruby-2.2.2@libv8/gems/libv8-3.16.14.7/ext/libv8/location.rb:26:in `install!'
	from extconf.rb:7:in `<main>'
GYP_GENERATORS=make \
build/gyp/gyp --generator-output="out" build/all.gyp \
              -Ibuild/standalone.gypi --depth=. \
              -Dv8_target_arch=x64 \
              -S.x64  -Dv8_enable_backtrace=1 -Dv8_can_use_vfp2_instructions=true -Darm_fpu=vfpv2 -Dv8_can_use_vfp3_instructions=true -Darm_fpu=vfpv3 -Dwerror=''
make[1]: Entering directory '/Users/cheba/.rvm/gems/ruby-2.2.2@libv8/gems/libv8-3.16.14.7/vendor/v8/out'
  CXX(target) /Users/cheba/.rvm/gems/ruby-2.2.2@libv8/gems/libv8-3.16.14.7/vendor/v8/out/x64.release/obj.target/preparser_lib/src/allocation.o
  CXX(target) /Users/cheba/.rvm/gems/ruby-2.2.2@libv8/gems/libv8-3.16.14.7/vendor/v8/out/x64.release/obj.target/preparser_lib/src/atomicops_internals_x86_gcc.o
  CXX(target) /Users/cheba/.rvm/gems/ruby-2.2.2@libv8/gems/libv8-3.16.14.7/vendor/v8/out/x64.release/obj.target/preparser_lib/src/bignum.o
  CXX(target) /Users/cheba/.rvm/gems/ruby-2.2.2@libv8/gems/libv8-3.16.14.7/vendor/v8/out/x64.release/obj.target/preparser_lib/src/bignum-dtoa.o
  CXX(target) /Users/cheba/.rvm/gems/ruby-2.2.2@libv8/gems/libv8-3.16.14.7/vendor/v8/out/x64.release/obj.target/preparser_lib/src/cached-powers.o
  CXX(target) /Users/cheba/.rvm/gems/ruby-2.2.2@libv8/gems/libv8-3.16.14.7/vendor/v8/out/x64.release/obj.target/preparser_lib/src/conversions.o
tools/gyp/preparser_lib.target.x64.mk:130: recipe for target '/Users/cheba/.rvm/gems/ruby-2.2.2@libv8/gems/libv8-3.16.14.7/vendor/v8/out/x64.release/obj.target/preparser_lib/src/conversions.o' failed
make[1]: Leaving directory '/Users/cheba/.rvm/gems/ruby-2.2.2@libv8/gems/libv8-3.16.14.7/vendor/v8/out'
Makefile:195: recipe for target 'x64.release' failed

extconf failed, exit code 1

Gem files will remain installed in /Users/cheba/.rvm/gems/ruby-2.2.2@libv8/gems/libv8-3.16.14.7 for inspection.
Results logged to /Users/cheba/.rvm/gems/ruby-2.2.2@libv8/extensions/x86_64-darwin-15/2.2.0/libv8-3.16.14.7/gem_make.out
```

I did a bit of digging in code and it seems like [`werror` should be off](https://github.com/cowboyd/libv8/blob/46132e848d52b4e04a320421d3d2eb451cdd14aa/ext/libv8/builder.rb#L46). But it looks like build system doesn't pick it up.

Workaround:

```
GCC_TREAT_WARNINGS_AS_ERRORS=NO gem install libv8
```

**Comment by tagliala** [comment]
same here, but the workaround doesn't work

```
$ GCC_TREAT_WARNINGS_AS_ERRORS=NO gem install libv8
Building native extensions.  This could take a while...
ERROR:  Error installing libv8:
	ERROR: Failed to build gem native extension.

    ~/.rvm/rubies/ruby-2.2.2/bin/ruby -r ./siteconf20150627-75361-1q2cx8e.rb extconf.rb
creating Makefile
Compiling v8 for x64
Using python 2.7.6
Using compiler: /usr/bin/c++ (clang version 6.1.0)
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool: file: ~/.rvm/gems/ruby-2.2.2/gems/libv8-3.16.14.8/vendor/v8/out/x64.release/obj.target/preparser_lib/src/atomicops_internals_x86_gcc.o has no symbols
In file included from ../src/accessors.cc:28:
In file included from ../src/v8.h:60:
In file included from ../src/objects-inl.h:38:
In file included from ../src/elements.h:33:
In file included from ../src/heap.h:35:
In file included from ../src/incremental-marking.h:33:
In file included from ../src/mark-compact.h:32:
../src/spaces.h:896:26: error: 'this' pointer cannot be null in well-defined C++ code; comparison may be assumed to always evaluate to true [-Werror,-Wtautological-undefined-compare]
  bool exists() { return this != NULL && code_range_ != NULL; }
                         ^~~~    ~~~~
../src/spaces.h:898:9: error: 'this' pointer cannot be null in well-defined C++ code; comparison may be assumed to always evaluate to false [-Werror,-Wtautological-undefined-compare]
    if (this == NULL || code_range_ == NULL) return false;
        ^~~~    ~~~~
2 errors generated.
make[1]: *** [~/.rvm/gems/ruby-2.2.2/gems/libv8-3.16.14.8/vendor/v8/out/x64.release/obj.target/v8_base/src/accessors.o] Error 1
make: *** [x64.release] Error 2
~/.rvm/gems/ruby-2.2.2/gems/libv8-3.16.14.8/ext/libv8/location.rb:36:in `block in verify_installation!': libv8 did not install properly, expected binary v8 archive '~/.rvm/gems/ruby-2.2.2/gems/libv8-3.16.14.8/vendor/v8/out/x64.release/obj.target/tools/gyp/libv8_base.a'to exist, but it was not found (Libv8::Location::Vendor::ArchiveNotFound)
	from ~/.rvm/gems/ruby-2.2.2/gems/libv8-3.16.14.8/ext/libv8/location.rb:35:in `each'
	from ~/.rvm/gems/ruby-2.2.2/gems/libv8-3.16.14.8/ext/libv8/location.rb:35:in `verify_installation!'
	from ~/.rvm/gems/ruby-2.2.2/gems/libv8-3.16.14.8/ext/libv8/location.rb:26:in `install!'
	from extconf.rb:7:in `<main>'
GYP_GENERATORS=make \
	build/gyp/gyp --generator-output="out" build/all.gyp \
	              -Ibuild/standalone.gypi --depth=. \
	              -Dv8_target_arch=x64 \
	              -S.x64  -Dv8_enable_backtrace=1 -Dv8_can_use_vfp2_instructions=true -Darm_fpu=vfpv2 -Dv8_can_use_vfp3_instructions=true -Darm_fpu=vfpv3 -Dwerror=''
  CXX(target) ~/.rvm/gems/ruby-2.2.2/gems/libv8-3.16.14.8/vendor/v8/out/x64.release/obj.target/preparser_lib/src/allocation.o
  CXX(target) ~/.rvm/gems/ruby-2.2.2/gems/libv8-3.16.14.8/vendor/v8/out/x64.release/obj.target/preparser_lib/src/atomicops_internals_x86_gcc.o
  CXX(target) ~/.rvm/gems/ruby-2.2.2/gems/libv8-3.16.14.8/vendor/v8/out/x64.release/obj.target/preparser_lib/src/bignum.o
  CXX(target) ~/.rvm/gems/ruby-2.2.2/gems/libv8-3.16.14.8/vendor/v8/out/x64.release/obj.target/preparser_lib/src/bignum-dtoa.o
  CXX(target) ~/.rvm/gems/ruby-2.2.2/gems/libv8-3.16.14.8/vendor/v8/out/x64.release/obj.target/preparser_lib/src/cached-powers.o
  CXX(target) ~/.rvm/gems/ruby-2.2.2/gems/libv8-3.16.14.8/vendor/v8/out/x64.release/obj.target/preparser_lib/src/conversions.o
  CXX(target) ~/.rvm/gems/ruby-2.2.2/gems/libv8-3.16.14.8/vendor/v8/out/x64.release/obj.target/preparser_lib/src/diy-fp.o
  CXX(target) ~/.rvm/gems/ruby-2.2.2/gems/libv8-3.16.14.8/vendor/v8/out/x64.release/obj.target/preparser_lib/src/dtoa.o
  CXX(target) ~/.rvm/gems/ruby-2.2.2/gems/libv8-3.16.14.8/vendor/v8/out/x64.release/obj.target/preparser_lib/src/fast-dtoa.o
  CXX(target) ~/.rvm/gems/ruby-2.2.2/gems/libv8-3.16.14.8/vendor/v8/out/x64.release/obj.target/preparser_lib/src/fixed-dtoa.o
  CXX(target) ~/.rvm/gems/ruby-2.2.2/gems/libv8-3.16.14.8/vendor/v8/out/x64.release/obj.target/preparser_lib/src/once.o
  CXX(target) ~/.rvm/gems/ruby-2.2.2/gems/libv8-3.16.14.8/vendor/v8/out/x64.release/obj.target/preparser_lib/src/preparse-data.o
  CXX(target) ~/.rvm/gems/ruby-2.2.2/gems/libv8-3.16.14.8/vendor/v8/out/x64.release/obj.target/preparser_lib/src/preparser.o
  CXX(target) ~/.rvm/gems/ruby-2.2.2/gems/libv8-3.16.14.8/vendor/v8/out/x64.release/obj.target/preparser_lib/src/preparser-api.o
  CXX(target) ~/.rvm/gems/ruby-2.2.2/gems/libv8-3.16.14.8/vendor/v8/out/x64.release/obj.target/preparser_lib/src/scanner.o
  CXX(target) ~/.rvm/gems/ruby-2.2.2/gems/libv8-3.16.14.8/vendor/v8/out/x64.release/obj.target/preparser_lib/src/strtod.o
  CXX(target) ~/.rvm/gems/ruby-2.2.2/gems/libv8-3.16.14.8/vendor/v8/out/x64.release/obj.target/preparser_lib/src/token.o
  CXX(target) ~/.rvm/gems/ruby-2.2.2/gems/libv8-3.16.14.8/vendor/v8/out/x64.release/obj.target/preparser_lib/src/unicode.o
  CXX(target) ~/.rvm/gems/ruby-2.2.2/gems/libv8-3.16.14.8/vendor/v8/out/x64.release/obj.target/preparser_lib/src/utils.o
  LIBTOOL-STATIC ~/.rvm/gems/ruby-2.2.2/gems/libv8-3.16.14.8/vendor/v8/out/x64.release/libpreparser_lib.a
  CXX(target) ~/.rvm/gems/ruby-2.2.2/gems/libv8-3.16.14.8/vendor/v8/out/x64.release/obj.target/preparser/preparser/preparser-process.o
  LINK(target) ~/.rvm/gems/ruby-2.2.2/gems/libv8-3.16.14.8/vendor/v8/out/x64.release/preparser
  CXX(target) ~/.rvm/gems/ruby-2.2.2/gems/libv8-3.16.14.8/vendor/v8/out/x64.release/obj.target/v8_base/src/accessors.o

extconf failed, exit code 1

Gem files will remain installed in ~/.rvm/gems/ruby-2.2.2/gems/libv8-3.16.14.8 for inspection.
Results logged to ~/.rvm/gems/ruby-2.2.2/extensions/x86_64-darwin-14/2.2.0/libv8-3.16.14.8/gem_make.out

```

**Comment by cowboyd** [comment]
There seems to be a funamental incompatibility with Clang 6.1 and this version of v8. I used gcc-4.2 (which can be found in `/usr/local/bin/g++-4.2`)

Also, I just released a new binary for darwin 14 https://rubygems.org/gems/libv8/versions/3.16.14.9-x86_64-darwin-14 which should let you install without compilation.

**Comment by tagliala** [comment]
thanks!

**Comment by tagliala** [comment]
Still having issues, 

osx 10.10.3, ruby 2.0.0p451

Maybe the ruby version?

```

Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

    ~/.rvm/rubies/ruby-2.0.0-p451/bin/ruby extconf.rb 
creating Makefile
Compiling v8 for x64
Using python 2.7.6
Using compiler: /usr/bin/c++ (clang version 6.1.0)
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool: file: ~/.rvm/gems/ruby-2.0.0-p451/gems/libv8-3.16.14.9/vendor/v8/out/x64.release/obj.target/preparser_lib/src/atomicops_internals_x86_gcc.o has no symbols
In file included from ../src/accessors.cc:28:
In file included from ../src/v8.h:60:
In file included from ../src/objects-inl.h:38:
In file included from ../src/elements.h:33:
In file included from ../src/heap.h:35:
In file included from ../src/incremental-marking.h:33:
In file included from ../src/mark-compact.h:32:
../src/spaces.h:896:26: error: 'this' pointer cannot be null in well-defined C++ code; comparison may be assumed to always evaluate to true [-Werror,-Wtautological-undefined-compare]
  bool exists() { return this != NULL && code_range_ != NULL; }
                         ^~~~    ~~~~
../src/spaces.h:898:9: error: 'this' pointer cannot be null in well-defined C++ code; comparison may be assumed to always evaluate to false [-Werror,-Wtautological-undefined-compare]
    if (this == NULL || code_range_ == NULL) return false;
        ^~~~    ~~~~
2 errors generated.
make[1]: *** [~/.rvm/gems/ruby-2.0.0-p451/gems/libv8-3.16.14.9/vendor/v8/out/x64.release/obj.target/v8_base/src/accessors.o] Error 1
make: *** [x64.release] Error 2
~/.rvm/gems/ruby-2.0.0-p451/gems/libv8-3.16.14.9/ext/libv8/location.rb:36:in `block in verify_installation!': libv8 did not install properly, expected binary v8 archive '~/.rvm/gems/ruby-2.0.0-p451/gems/libv8-3.16.14.9/vendor/v8/out/x64.release/obj.target/tools/gyp/libv8_base.a'to exist, but it was not found (Libv8::Location::Vendor::ArchiveNotFound)
	from ~/.rvm/gems/ruby-2.0.0-p451/gems/libv8-3.16.14.9/ext/libv8/location.rb:35:in `each'
	from ~/.rvm/gems/ruby-2.0.0-p451/gems/libv8-3.16.14.9/ext/libv8/location.rb:35:in `verify_installation!'
	from ~/.rvm/gems/ruby-2.0.0-p451/gems/libv8-3.16.14.9/ext/libv8/location.rb:26:in `install!'
	from extconf.rb:7:in `<main>'
GYP_GENERATORS=make \
	build/gyp/gyp --generator-output="out" build/all.gyp \
	              -Ibuild/standalone.gypi --depth=. \
	              -Dv8_target_arch=x64 \
	              -S.x64  -Dv8_enable_backtrace=1 -Dv8_can_use_vfp2_instructions=true -Darm_fpu=vfpv2 -Dv8_can_use_vfp3_instructions=true -Darm_fpu=vfpv3 -Dwerror=''
  CXX(target) ~/.rvm/gems/ruby-2.0.0-p451/gems/libv8-3.16.14.9/vendor/v8/out/x64.release/obj.target/preparser_lib/src/allocation.o
  CXX(target) ~/.rvm/gems/ruby-2.0.0-p451/gems/libv8-3.16.14.9/vendor/v8/out/x64.release/obj.target/preparser_lib/src/atomicops_internals_x86_gcc.o
  CXX(target) ~/.rvm/gems/ruby-2.0.0-p451/gems/libv8-3.16.14.9/vendor/v8/out/x64.release/obj.target/preparser_lib/src/bignum.o
  CXX(target) ~/.rvm/gems/ruby-2.0.0-p451/gems/libv8-3.16.14.9/vendor/v8/out/x64.release/obj.target/preparser_lib/src/bignum-dtoa.o
  CXX(target) ~/.rvm/gems/ruby-2.0.0-p451/gems/libv8-3.16.14.9/vendor/v8/out/x64.release/obj.target/preparser_lib/src/cached-powers.o
  CXX(target) ~/.rvm/gems/ruby-2.0.0-p451/gems/libv8-3.16.14.9/vendor/v8/out/x64.release/obj.target/preparser_lib/src/conversions.o
  CXX(target) ~/.rvm/gems/ruby-2.0.0-p451/gems/libv8-3.16.14.9/vendor/v8/out/x64.release/obj.target/preparser_lib/src/diy-fp.o
  CXX(target) ~/.rvm/gems/ruby-2.0.0-p451/gems/libv8-3.16.14.9/vendor/v8/out/x64.release/obj.target/preparser_lib/src/dtoa.o
  CXX(target) ~/.rvm/gems/ruby-2.0.0-p451/gems/libv8-3.16.14.9/vendor/v8/out/x64.release/obj.target/preparser_lib/src/fast-dtoa.o
  CXX(target) ~/.rvm/gems/ruby-2.0.0-p451/gems/libv8-3.16.14.9/vendor/v8/out/x64.release/obj.target/preparser_lib/src/fixed-dtoa.o
  CXX(target) ~/.rvm/gems/ruby-2.0.0-p451/gems/libv8-3.16.14.9/vendor/v8/out/x64.release/obj.target/preparser_lib/src/once.o
  CXX(target) ~/.rvm/gems/ruby-2.0.0-p451/gems/libv8-3.16.14.9/vendor/v8/out/x64.release/obj.target/preparser_lib/src/preparse-data.o
  CXX(target) ~/.rvm/gems/ruby-2.0.0-p451/gems/libv8-3.16.14.9/vendor/v8/out/x64.release/obj.target/preparser_lib/src/preparser.o
  CXX(target) ~/.rvm/gems/ruby-2.0.0-p451/gems/libv8-3.16.14.9/vendor/v8/out/x64.release/obj.target/preparser_lib/src/preparser-api.o
  CXX(target) ~/.rvm/gems/ruby-2.0.0-p451/gems/libv8-3.16.14.9/vendor/v8/out/x64.release/obj.target/preparser_lib/src/scanner.o
  CXX(target) ~/.rvm/gems/ruby-2.0.0-p451/gems/libv8-3.16.14.9/vendor/v8/out/x64.release/obj.target/preparser_lib/src/strtod.o
  CXX(target) ~/.rvm/gems/ruby-2.0.0-p451/gems/libv8-3.16.14.9/vendor/v8/out/x64.release/obj.target/preparser_lib/src/token.o
  CXX(target) ~/.rvm/gems/ruby-2.0.0-p451/gems/libv8-3.16.14.9/vendor/v8/out/x64.release/obj.target/preparser_lib/src/unicode.o
  CXX(target) ~/.rvm/gems/ruby-2.0.0-p451/gems/libv8-3.16.14.9/vendor/v8/out/x64.release/obj.target/preparser_lib/src/utils.o
  LIBTOOL-STATIC ~/.rvm/gems/ruby-2.0.0-p451/gems/libv8-3.16.14.9/vendor/v8/out/x64.release/libpreparser_lib.a
  CXX(target) ~/.rvm/gems/ruby-2.0.0-p451/gems/libv8-3.16.14.9/vendor/v8/out/x64.release/obj.target/preparser/preparser/preparser-process.o
  LINK(target) ~/.rvm/gems/ruby-2.0.0-p451/gems/libv8-3.16.14.9/vendor/v8/out/x64.release/preparser
  CXX(target) ~/.rvm/gems/ruby-2.0.0-p451/gems/libv8-3.16.14.9/vendor/v8/out/x64.release/obj.target/v8_base/src/accessors.o

extconf failed, exit code 1

Gem files will remain installed in ~/.rvm/gems/ruby-2.0.0-p451/gems/libv8-3.16.14.9 for inspection.
Results logged to ~/.rvm/gems/ruby-2.0.0-p451/extensions/x86_64-darwin-12/2.0.0-static/libv8-3.16.14.9/gem_make.out
An error occurred while installing libv8 (3.16.14.9), and Bundler cannot continue.
Make sure that `gem install libv8 -v '3.16.14.9'` succeeds before bundling.
```

**Comment by cowboyd** [comment]
What version of rubygems are you using?

**Comment by tagliala** [comment]
```sh
$ gem -v
2.4.6
```

**Comment by tagliala** [comment]
Sorry...

```sh
$ gem -v
2.2.2
```

updated to 2.4.8, same error, different version of libv8 (3.16.14.8).
