### ISSUE TITLE
Enable i18n support

### ISSUE THREAD

**Issue by gschlager** [cowboyd/libv8#278]
It looks like the following line prevents V8 from compiling with the `V8_INTL_SUPPORT` feature flag.

https://github.com/cowboyd/libv8/blob/2057f4683d0ed9df3a4880c21b67e47280dd436c/ext/libv8/builder.rb#L27

Without it things like Unicode Property Escapes do not work. For example, the following code snippet should work since V8 6.6, but it throws an error in `MiniRacer`.
```ruby
MiniRacer::Context.new.eval('/[\p{Alphabetic}]/u.test("Jørn")')
```

Could you please compile a version with i18n support enabled?

**Comment by ignisf** [comment]
Hi,

I've released a beta version with I18n enabled and debugging symbols. You should be able to take it for a spin by pinning to it.

![image](https://user-images.githubusercontent.com/1153188/57284692-5ee7fa80-70ba-11e9-9032-5f3d940730f2.png)

**Comment by gschlager** [comment]
Thanks! It's still not working for me. I tested with the following code:

```ruby
MiniRacer::Context.new.eval('/[\p{Alphabetic}]/u.test("Jørn")')
MiniRacer::Context.new.eval("typeof Intl === 'object'")
```

According to https://v8.dev/docs/i18n you are doing everything right. `v8_enable_i18n_support` is enabled and `MiniRacer` tries to [initialize ICU](https://github.com/discourse/mini_racer/blob/cad52dfcb10c384eae7f7b076a3d3b3b65022a62/ext/mini_racer_extension/mini_racer_extension.cc#L189).

I see that the gem grew in size and that it ships with 2 new ICU libs, but maybe it's not using the libs at runtime? Should `Libv8::Paths.object_paths` reference the ICU libs?

**Comment by ignisf** [comment]
I think you're on to something, will take a look if I need to change the ldflags

**Comment by gschlager** [comment]
I'm not sure why, but the i18n methods in this beta version started working with the release of mini_racer 0.2.6 🤷‍♂

**Comment by ignisf** [comment]
good to know... was wondering why I couldn't reproduce the issue

**Comment by ignisf** [comment]
mini racer needed to be recompiled with the i18n enabled v8
